;TODO use doto

(ns life-game.life
  (:require [life-game.data.cell :as cell]
            [clojure.set         :as cset]))

(defn- new-cell-from-vec
  "Return new Cell instance from vector [x y]"
  [[a b]]
  (cell/new-cell a b))

(defn- spread
  "Return set of c + surronded cells"
  [c]
  (let [x (.x c)
        y (.y c)
        xs [(dec x) x (inc x)]
        ys [(dec y) y (inc y)]
        vecs (set (for [a xs b ys] [a b]))]
    (map new-cell-from-vec vecs)))

(defn- live?
  "The predicate of that cell is lived ?"
  [c prev-cells]
  (let [ss (set (spread c))
        ss' (cset/difference ss #{c})
        ss'' (cset/intersection ss' prev-cells)]
    (>= (count ss'') 3)))

(defn birth
  "Return birthed cell-set, cell-set was generated by existing cell-set"
  [prev-cells]
  (let [spread-cells (set (flatten (map spread prev-cells)))
        surround-cells (cset/difference spread-cells prev-cells)]
    (set (for [z surround-cells :when (live? z prev-cells)] z))))
